# Generated by Django 3.2.19 on 2023-06-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegram',
            options={'verbose_name': 'Telegram profile', 'verbose_name_plural': 'Telegram profiles'},
        ),
    ]
