# Generated by Django 3.2.19 on 2023-06-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='telegram',
            index=models.Index(fields=['user_id'], name='telegram_user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='telegram',
            index=models.Index(fields=['username'], name='telegram_username_idx'),
        ),
    ]
