version: '3.4'

services:
  postgres:
    image: postgres:12.12-alpine
    container_name: postgres
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
  
  celeryworker:
    container_name: celeryworker
    build:
      context: django_search/
      dockerfile: Dockerfile
    command: celery -A django_search worker -P treads --pool=prefork -l info
    volumes: 
      - ./django_search:/home/app/web
    env_file:
      - ./.env
    depends_on:
      - redis
  
  celeryscheduler:
    container_name: celeryscheduler
    build:
      context: django_search/
      dockerfile: Dockerfile
    command: celery -A django_search beat -l info
    volumes:
      - ./django_search:/home/app/web
    env_file:
      - ./.env
    depends_on:
      - redis

  # flower:
  #   container_name: flower
  #   build:
  #     context: django_search/
  #     dockerfile: Dockerfile
  #   command: celery -A django_search flower
  #   ports:
  #     - 5555:5555
  #   env_file:
  #     - ./.env

  web:
    container_name: web
    build:
      context: django_search/
      dockerfile: Dockerfile
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_search:/home/app/web
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - redis

  bot:
    container_name: bot
    build:
      context: django_search/
      dockerfile: Dockerfile
    restart: always
    command: python manage.py bot
    volumes:
      - ./django_search:/home/app/web
    env_file:
      - ./.env
