version: '3.4'

services:
  postgres:
    image: postgres:12.12-alpine
    container_name: postgres
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    env_file:
      - ./.env
    ports:
      - 15672:15672
      - 5672:5672

  celeryworker:
    container_name: celeryworker
    build:
      context: django_search/
      dockerfile: Dockerfile
    command: celery -A django_search.celery.app worker --pool=prefork -l info
    volumes:
      - ./django_search:/app/web
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
  
  celeryscheduler:
    container_name: celeryscheduler
    build:
      context: django_search/
      dockerfile: Dockerfile
    command: celery -A django_search beat -l info
    volumes:
      - ./django_search:/app/web
    env_file:
      - ./.env
    depends_on:
      - rabbitmq

  web:
    container_name: web
    build:
      context: django_search/
      dockerfile: Dockerfile
    restart: always
    command: gunicorn django_search.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./django_search/staticfiles:/app/web/staticfiles
      - ./django_search/mediafiles:/home/app/web/mediafiles
    env_file:
      - ./.env
    expose:
      - 8000
    depends_on:
      - postgres
      - rabbitmq
  
  bot:
    container_name: bot
    build:
      context: django_search/
      dockerfile: Dockerfile
    restart: always
    command: python manage.py bot
    volumes:
      - ./django_search:/app/web
    env_file:
      - ./.env

  nginx:
    container_name: nginx
    build:
      context:  nginx/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - ./django_search/staticfiles:/app/web/staticfiles
      - ./django_search/mediafiles:/home/app/web/mediafiles
    depends_on:
      - web
