# Generated by Django 3.2.19 on 2023-06-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20230615_2220'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_by'], name='ticket_created_by_idx'),
        ),
    ]
