# Generated by Django 3.2.19 on 2023-06-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_ticket_created_by_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='url',
            field=models.URLField(max_length=1536),
        ),
    ]
