# Generated by Django 3.2.19 on 2023-06-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='url',
            field=models.URLField(max_length=1024),
        ),
    ]
