# Generated by Django 3.2.19 on 2023-05-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20230514_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
