# Generated by Django 3.2.19 on 2023-05-26 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('tickets', '0008_alter_ticket_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='telegram_id',
            new_name='telegram_username',
        ),
        migrations.AddField(
            model_name='ticket',
            name='telegram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='profiles.telegram'),
        ),
    ]
