# Generated by Django 3.2.19 on 2023-05-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20230526_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fff',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
