# Generated by Django 3.2.19 on 2023-05-26 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticket_fff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='fff',
        ),
    ]
