# Generated by Django 3.2.19 on 2023-05-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='url',
            field=models.URLField(max_length=1024),
        ),
    ]
