# Generated by Django 3.2.19 on 2023-05-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='telegram_id'),
        ),
    ]
