# Generated by Django 3.2.19 on 2023-05-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_telegram_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram',
            name='telegram_id',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='telegram_id'),
            preserve_default=False,
        ),
    ]
